package demo.hw.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.15
 * 2018-11-28T14:24:37.436+08:00
 * Generated source version: 3.1.15
 * 
 */
@WebService(targetNamespace = "http://server.hw.demo/", name = "HelloWorld2")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld2 {

    @WebMethod
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://server.hw.demo/", className = "demo.hw.server.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://server.hw.demo/", className = "demo.hw.server.SayHiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
